### ISSUE TITLE
Support Annotations version references non-existant value

### ISSUE THREAD

**Issue by jackmalpo** [schlan/picassocompat#6]
If you look at  https://github.com/schlan/picassocompat/blob/80d5e5e1de5ff72bac36cc0ce3754660ccf595e4/picassocompat/build.gradle#L30

It references `versions.supportLibVersion` which is not defined

It should reference `versions.annotations`

**Comment by jackmalpo** [comment]
@schlan any chance this is something that could be fixed soon? if not I can make a PR. causing issue for a downstream client of ours 😬

**Comment by jackmalpo** [comment]
@schlan Opened a PR :) Would love to get a new release out asap if possible

**Comment by schlan** [comment]
@jackmalpo i've released v1.2.1 with your fix, please let me know if there are any more issues

**Comment by jackmalpo** [comment]
Awesome. Much appreciated!
